
#Integration options for JEI (Just Enough Items)
["JEI Settings"]
	#Set this to false to disable JEI integration functionality.
	jei = true

#Integration options for JER (Just Enough Resources)
["JER Settings"]
	#Set this to false to disable JER integration functionality.
	jer = true

#Integration options for Immersive Engineering
["Immersive Engineering Settings"]
	#Set this to false to disable Immersive Engineering integration functionality.
	immersiveEngineering = true

