["Better Caves"."Underground Generation".Caves."Type 2 Caves"]
"Type 2 Cave Priority" = 7

["Better Caves"."Underground Generation".Caverns]
"Cavern Spawn Chance" = 60.0
"Cavern Region Size" = "Custom"
"Cavern Region Size Custom Value" = 0.00425

["Better Caves"."Underground Generation".Caverns."Floored Caverns"]
"Floored Cavern Maximum Altitude" = 42
"Compression - Vertical" = 0.95
"Compression - Horizontal" = 0.35
"Floored Cavern Priority" = 10

["Better Caves"."Underground Generation".Caverns."Liquid Caverns"]
"Liquid Cavern Maximum Altitude" = 42
"Compression - Vertical" = 0.95
"Compression - Horizontal" = 0.65
"Liquid Cavern Priority" = 6

["Better Caves"."Underground Generation".Ravines]
"Enable Ravines" = false
"Enable Flooded Ravines" = false

["Better Caves"."Underground Generation"."Water Regions"]
"Water Region Spawn Chance" = 50.0

["Better Caves"."Underground Generation".Miscellaneous]
"Liquid Altitude" = 9
