Version: 1
ModpackName: "Colorful Skies"
Overworld:
  PresetFolderName: "Far From Home 7 Premium"
Dimensions:
- PresetFolderName: "VanillaVistas"
  Seed: 140055
GameRules:
  DoFireTick: true
  MobGriefing: true
  KeepInventory: true
  DoMobSpawning: true
  DoMobLoot: true
  DoTileDrops: true
  DoEntityDrops: true
  CommandBlockOutput: true
  NaturalRegeneration: true
  DoDaylightCycle: true
  LogAdminCommands: true
  ShowDeathMessages: true
  RandomTickSpeed: 3
  SendCommandFeedback: true
  SpectatorsGenerateChunks: true
  SpawnRadius: 10
  DisableElytraMovementCheck: true
  MaxEntityCramming: 24
  DoWeatherCycle: true
  DoLimitedCrafting: false
  MaxCommandChainLength: 65536
  AnnounceAdvancements: true
  DisableRaids: false
  DoInsomnia: false
  DrowningDamage: true
  FallDamage: true
  FireDamage: true
  DoPatrolSpawning: true
  DoTraderSpawning: true
  ForgiveDeadPlayers: true
  UniversalAnger: false
