(define (cs-maybe-layer image layer)
    (if (null? layer) (car (gimp-image-get-active-layer image)) layer)
)
(define (cs-maybe-layer-by-name image layer)
    (if (null? layer) (car (gimp-image-get-active-layer image)) (car (gimp-image-get-layer-by-name image layer)))
)

(define (cs-load-xcf path)
    (begin (display "- Loading image from '") (display path) (display "'...") (newline))
    (car (gimp-xcf-load RUN-NONINTERACTIVE path path))
)
(define (cs-load-png path)
    (begin (display "- Loading image from '") (display path) (display "'...") (newline))
    (car (file-png-load RUN-NONINTERACTIVE path path))
)
(define (cs-new-layer image name)
    (let 
        ((new-layer (car (gimp-layer-new
            image (car (gimp-image-width image)) (car (gimp-image-height image))
            RGBA-IMAGE name 100 LAYER-MODE-NORMAL
        ))))
        (gimp-image-insert-layer image new-layer 0 0)
        new-layer
    )
)
(define (cs-append-layer image parent layer)
    (gimp-image-reorder-item image layer parent (car (gimp-item-get-children parent)))
)
(define (cs-transfer-image-to-layer source source_layer target_layer)
    (gimp-edit-copy (cs-maybe-layer-by-name source source_layer))
    (gimp-edit-paste target_layer 0)
)
(define (cs-png-save image layer target)
    (begin (display "- Creating image at '") (display target) (display "'...") (newline))
    (file-png-save RUN-NONINTERACTIVE image (cs-maybe-layer image layer) target target 0 5 0 0 0 0 1)
)
